import os
from fastapi import APIRouter, Depends, Request
from pydantic import BaseModel
from typing import List, Tuple
from security import get_current_user
from rate_limiter import limiter
import structlog

log = structlog.get_logger("shield-safe-network")

router = APIRouter(prefix="/api/v1/community", tags=["Community"])

class RouteData(BaseModel):
    # E.g., a list of coordinates [ [lon, lat], [lon, lat] ] 
    # generated by Google Maps / Mapbox directions api
    route_points: List[Tuple[float, float]] 
    estimated_duration_minutes: int

class SafeNetwork:
    """
    The Viral Moat: Anonymized Community Power.
    """
    def __init__(self, db_pool):
        self.db_pool = db_pool

    async def register_and_match_commute(self, user_id: str, route: RouteData):
        """
        Registers the user's route as a PostGIS LineString, then checks if any
        other user is traveling along an intersecting route at the same time.
        """
        async with self.db_pool.acquire() as conn:
            # 1. Convert the list of arrays into a PostGIS LineString WKT format
            # PostGIS LineStrings expect 'LINESTRING(lon lat, lon lat, ...)'
            linestring_wkt = "LINESTRING(" + ", ".join([f"{lon} {lat}" for lon, lat in route.route_points]) + ")"
            
            # 2. Insert this active commute so others can match with it
            # We assume an `active_commutes` table exists in the schema just for this.
            # (In production, this table would have a TTL / pg_cron job to delete old rows)
            try:
                await conn.execute("""
                    CREATE TABLE IF NOT EXISTS active_commutes (
                        user_id UUID PRIMARY KEY,
                        route geometry(LineString, 4326),
                        expires_at TIMESTAMP WITH TIME ZONE
                    );
                    CREATE INDEX IF NOT EXISTS idx_commutes_geom ON active_commutes USING GIST(route);
                """)
                
                await conn.execute("""
                    INSERT INTO active_commutes (user_id, route, expires_at)
                    VALUES ($1, ST_GeomFromText($2, 4326), NOW() + INTERVAL '1 minute' * $3)
                    ON CONFLICT (user_id) DO UPDATE 
                    SET route = EXCLUDED.route, expires_at = EXCLUDED.expires_at;
                """, user_id, linestring_wkt, route.estimated_duration_minutes)
            except Exception as e:
                log.error("Failed to register commute geometry", error=str(e))
            
            # 3. Find Overlapping Routes (The Magic Moat)
            # Find any commutes that are within 50 meters of our intended route,
            # excluding ourselves, that haven't expired.
            # ST_DWithin strictly checks if the exact paths parallel each other over geographic space.
            matches = await conn.fetch("""
                SELECT user_id 
                FROM active_commutes 
                WHERE user_id != $1
                  AND expires_at > NOW()
                  AND ST_DWithin(
                      route::geography, 
                      ST_GeomFromText($2, 4326)::geography, 
                      50  -- 50 meters tolerance (walking on same street)
                  )
            """, user_id, linestring_wkt)

        # 4. If we found matches, we would theoretically trigger a silent push notification
        # to BOTH users (via their FCM tokens) saying: 
        # "Someone is commuting your route. You are both being monitored."
        has_buddies = len(matches) > 0
        
        if has_buddies:
            log.info("safe.network.match_found", users_matched=len(matches), trigger=user_id)
            
        return {
            "commute_registered": True,
            "buddies_found": len(matches),
            "message": "Someone is commuting near you. You are both being monitored." if has_buddies else "Route registered securely."
        }

@router.post("/commute-buddy")
@limiter.limit("5/minute")
async def start_safe_commute(
    request: Request,
    route: RouteData,
    current_user: dict = Depends(get_current_user)
):
    """
    Users call this when they are about to walk home from a transit stop or take an unfamiliar route.
    """
    db_pool = request.app.state.db_pool
    network = SafeNetwork(db_pool=db_pool)
    
    result = await network.register_and_match_commute(str(current_user["user_id"]), route)
    return result
